### ISSUE TITLE
Форма ввода проекта - Уточнить максимально допустимое количество привязанных к проекту задач, создаваемых в форме ввода задач

### ISSUE THREAD

**Issue by weronikalisay7** [weronikalisay7/qulix.Internship#1]
В спецификации требований "Приложение для управления задачами" не описано максимально допустимое количество задачах, которые могут быть привязаны к одному проекту. Требуется уточнение.

**Comment by VashinaNatalia** [comment]
@weronikalisay7 мы не ограничиваем конкретным количеством.
См. "Между перечисленными выше объектами необходимо реализовать следующие связи:
-	Проект может включать в себя от нуля до множества задач
-	Одна персона может быть назначена на множество задач
-	Дополнительное требование: одна и та же задача может выполняться множеством персон"
