### ISSUE TITLE
Форма ввода задачи - Уточнить должен ли отображаться список проектов при открытии формы ввода задач из формы ввода проектов

### ISSUE THREAD

**Issue by weronikalisay7** [weronikalisay7/qulix.Internship#2]
В спецификации требований "Приложение для управления задачами" п. "Форма ввода задачи" не описано отображение списка проектов после открытия формы ввода задач из формы ввода проектов. Требуется уточнение.

**Comment by VashinaNatalia** [comment]
@weronikalisay7 в пункте 6. "Форма ввода задачи" указано следующее:
_Поле "Проект": выбирается из списка проектов; если форма открыта из списка задач формы ввода проектов, то данное поле установлено равным текущему проекту и недоступно для редактирования_
