### ISSUE TITLE
Форма ввода проекта - Уточнить минимально и максимально допустимое количество символов, которые может содержать поле "Название"

### ISSUE THREAD

**Issue by weronikalisay7** [weronikalisay7/qulix.Internship#3]
В спецификации требований "Приложение для управления задачами" п. "Форма ввода проекта" не указано минимально и максимально допустимое количество символов, которые может содержать поле "Название" (так же поля "Сокращенное Название" и "Описание"). Требуется уточнение.

**Comment by VashinaNatalia** [comment]
@weronikalisay7 
Поле "Название": от 5 до 50 символов
Поле "Сокращенное название": от 2 до 40 символов
Поле "Описание": от 10 до 255 символов
